name: Build and Push Ubuntu Images

on:
  push:
    branches:
      - main
    paths:
      - "ubuntu/*"
  workflow_dispatch: { }
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build-and-push-ubuntu-images:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get packages list
        id: get-packages-list
        run: |
          packages=$(echo $(cat "ubuntu/packages" 2>/dev/null))
          echo "::set-output name=packages::$packages"

      - name: Build and push Ubuntu Jammy (latest LTS)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ubuntu/Dockerfile.jammy
          build-args: packages=${{ steps.get-packages-list.outputs.packages }}
          tags: bhenao/ubuntu:jammy,bhenao/ubuntu:latest

      - name: Build and push Ubuntu Bionic
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ubuntu/Dockerfile.bionic
          build-args: packages=${{ steps.get-packages-list.outputs.packages }}
          tags: bhenao/ubuntu:bionic